name: nodejs ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: init nodejs
        uses: ./.github/actions/init
        with:
          nodejs-version: ${{ matrix.node-version }}
      - name: build
        shell: bash
        run: npm run build --if-present
      - name: test
        shell: bash
        run: npm test
